### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by MariuszPL55** [gilgame/SEWorkbench#19]
This IDE even not start.. When I choose SpaceEngineers.exe from Bin64 then I had error some about image format, now in Bin I have this: An unhandled exception of type 'System.TypeLoadException' occurred in Gilgame.SEWorkbench.Interop.dll

Additional information: Nie można załadować typu (Can't load a type) 'Sandbox.Common.ObjectBuilders.MyObjectBuilder_SessionSettings' z zestawu 'VRage.Game, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by gilgame** [comment]
Hey, yeah sorry. The TypeLoadException is due to Keen moving objects around to different namespaces and libraries. This will likely break Workbench every Thursday until they are finished. I've brought Workbench up to date and the latest release should be working: https://github.com/gilgame/SEWorkbench/releases/tag/1010
