### ISSUE TITLE
Crash on start #2

### ISSUE THREAD

**Issue by HeavyShadow** [gilgame/SEWorkbench#23]
Hello,
After i try to start it asks for the space engineers exe, i locate it, win "u sure u wanna run it?" message, i click ok, and this is what i get:
"(System.IO.FileNotFoundException) Could not load file or assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

   at Gilgame.SEWorkbench.Interop.Engine.SetPaths()
   at Gilgame.SEWorkbench.Interop.Engine.Initialize()
   at Gilgame.SEWorkbench.Program.Main(String[] args)"

Could You help me please?
Thanks,
Shadow

**Comment by MariuszPL55** [comment]
You probarly don't receive any help from that project, it looks like it stay in place for long time. Look for example for one pull request that was created about 4 months ago and author don't even probarly look at it. I don't say that project is stupid, because it would be genius, I only say that the author probarly don't have any time for that project.

**Comment by gilgame** [comment]
Duplicate https://github.com/gilgame/SEWorkbench/issues/22
